Practice with fft 

In [10]:
import numpy as np
import matplotlib.pyplot as plt

In [37]:
a=np.zeros((10, 5))
print(a)
d=np.empty((10, 5))
##si no quiero decimales le agrego el d=np.empty((10, 5), int)
print(d)
b=np.arange(6) #es un vector de 1x6 1 fila 6 columnas.
print("b es un vector de 1x6 1 fila 6 columnas", b)
c=b.reshape((3,2)) #reshape, indica que voy a ordenar ese mismo vector, pero en 3 filas y 2 columnas.
print("c es un vector que se le cambia la forma de la b pero contiene la misma informacion",c)
z,p=6,7
print(z)
print(p)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
b es un vector de 1x6 1 fila 6 columnas [0 1 2 3 4 5]
c es un vector que se le cambia la forma de la b pero contiene la misma infomracion [[0 1]
 [2 3]
 [4 5]]
6
7


Hagamos un loop ahora

In [21]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [28]:
for i in range(1, 11):
    print(i)

1
2
3
4
5
6
7
8
9
10


In [32]:
for i in range(1,11):
 for j in range (1,6):
    testloop=d((i,j))
    
print(testloop)

TypeError: 'numpy.ndarray' object is not callable

In [29]:
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
